//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConnect.DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HranitelPROEntities : DbContext
    {
        public HranitelPROEntities()
            : base("name=HranitelPROEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Subdivision> Subdivision { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<VisitPurpose> VisitPurpose { get; set; }
        public virtual DbSet<VisitRejectionPurpose> VisitRejectionPurpose { get; set; }
        public virtual DbSet<VisitRequest> VisitRequest { get; set; }
        public virtual DbSet<VisitStatus> VisitStatus { get; set; }
        public virtual DbSet<VisitTimeSpans> VisitTimeSpans { get; set; }
        public virtual DbSet<VisitType> VisitType { get; set; }
    }
}
