//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConnect.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.VisitRequest = new HashSet<VisitRequest>();
        }
    
        public int UserID { get; set; }
        public string UserSurname { get; set; }
        public string UserName { get; set; }
        public string UserPatronymic { get; set; }
        public string UserPhone { get; set; }
        public string UserEmail { get; set; }
        public Nullable<System.DateTime> UserDateofBirth { get; set; }
        public string UserPassportSeries { get; set; }
        public string UserPassportNumber { get; set; }
        public string UserPassportScan { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
        public string UserOrganization { get; set; }
        public byte[] UserPhoto { get; set; }
        public Nullable<bool> UserBlackList { get; set; }
        public Nullable<int> UserIncorrectDataCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitRequest> VisitRequest { get; set; }
    }
}
