//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConnect.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitTimeSpans
    {
        public int VisitID { get; set; }
        public Nullable<System.DateTime> VisitDateTime { get; set; }
        public Nullable<System.DateTime> CheckPointIncome { get; set; }
        public Nullable<System.DateTime> CheckpointOutcome { get; set; }
        public Nullable<System.DateTime> SubdivisionIncome { get; set; }
        public Nullable<System.DateTime> SubdivisionOutcome { get; set; }
    
        public virtual VisitRequest VisitRequest { get; set; }
    }
}
