//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConnect.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitRequest
    {
        public int VisitRequestID { get; set; }
        public Nullable<int> VisitUser { get; set; }
        public Nullable<int> VisitSubdivision { get; set; }
        public Nullable<int> VisitEmployee { get; set; }
        public Nullable<System.DateTime> VisitDateStart { get; set; }
        public Nullable<System.DateTime> VisitDateEnd { get; set; }
        public Nullable<int> VisitPurpose { get; set; }
        public Nullable<int> VisitType { get; set; }
        public string VisitorsList { get; set; }
        public string VisitNote { get; set; }
        public Nullable<int> VisitStatus { get; set; }
        public Nullable<int> VisitRejectionPurpose { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Subdivision Subdivision { get; set; }
        public virtual User User { get; set; }
        public virtual VisitPurpose VisitPurpose1 { get; set; }
        public virtual VisitRejectionPurpose VisitRejectionPurpose1 { get; set; }
        public virtual VisitStatus VisitStatus1 { get; set; }
        public virtual VisitType VisitType1 { get; set; }
        public virtual VisitTimeSpans VisitTimeSpans { get; set; }
    }
}
